# --- CONNECTED COMPONENTS ---
HIGHLY_FRAGMENTED_MULTIPLIER = 1.5
AREA_BLUR_CUTOFF_MULTIPLIER = 12.0
BLUR_KERNEL_SIZE_MULTIPLIER = 0.3
LENIENCY_SMALL_COMPONENTS_MULTIPLIER = 0.75

# --- CHARACTER SEGMENTATION ---
CHARACTER_LENGTH_ESTIMATE_MULTIPLIER = 1.5
PROJ_PEAK_FRACTION_THRESH = 0.5

# --- LINE SEGMENTATION ---
KDE_BANDWIDTH = 25.0
